FROM python:3.12-slim

WORKDIR /app
COPY ./requirements.txt /tmp/requirements.txt
RUN apt-get update && apt-get upgrade -y

RUN pip install --upgrade pip
RUN pip install -r /tmp/requirements.txt --no-cache-dir
